exclude: .*migrations\/.*
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  # Run the linter.
  - id: ruff
  # Run the formatter.
  - id: ruff-format
